version: "3.6"
services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
 
 
  opentelemetry-ms-1:
     build: spboot-tracing-ms1
     ports:
      - 8081:8081
 
  opentelemetry-ms-2:
     build: spboot-tracing-ms2
     ports:
      - 8080:8080
